/-
Copyright (c) 2026 Aalok Thakkar. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aalok Thakkar
-/
module

public import Mathlib.Computability.ContextFreeGrammar

@[expose] public section

/-!
# CFG-Intersection Emptiness

The decision problem **CFG-intersection emptiness** asks: given two
context-free grammars `G₁` and `G₂`, is `L(G₁) ∩ L(G₂) = ∅`?

This is one of the standard problems shown undecidable by reduction
from PCP (Hopcroft & Ullman, *Introduction to Automata Theory,
Languages, and Computation*, Theorem 8.10). The reduction is built in
`CFG.PcpReduction`.

This file just states the two decision predicates and a small bridging
lemma. It does **not** prove undecidability — that would require
combining the reduction with a proof of PCP undecidability, which is
not in this repository (see the top-level README).
-/

namespace CFG

/-- The decision predicate **"the intersection of `G₁` and `G₂` is
empty"**: no word is generated by both grammars. -/
def IntersectionEmpty {T : Type} (G₁ G₂ : ContextFreeGrammar T) : Prop :=
  ∀ w : List T, ¬ (w ∈ G₁.language ∧ w ∈ G₂.language)

/-- The complementary decision predicate: some word is generated by both
grammars. -/
def IntersectionNonempty {T : Type} (G₁ G₂ : ContextFreeGrammar T) : Prop :=
  ∃ w : List T, w ∈ G₁.language ∧ w ∈ G₂.language

lemma not_intersectionEmpty_iff_nonempty {T : Type}
    (G₁ G₂ : ContextFreeGrammar T) :
    ¬ IntersectionEmpty G₁ G₂ ↔ IntersectionNonempty G₁ G₂ := by
  unfold IntersectionEmpty IntersectionNonempty
  push_neg
  rfl

end CFG
