/-
Copyright (c) 2026 Aalok Thakkar. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aalok Thakkar
-/
module

public import CFG.Basic
public import PCP.Basic

@[expose] public section

/-!
# `PCP ≤_m` CFG-Intersection-Nonemptiness

Given a PCP instance `P : Stack α`, we build two single-nonterminal
context-free grammars `topCFG P` and `botCFG P` over a terminal alphabet
`α ⊕ Tile α` (PCP symbols on the `.inl` side, tile markers on the
`.inr` side) such that

```
HasSolution P ↔ ∃ w, w ∈ (topCFG P).language ∧ w ∈ (botCFG P).language.
```

## Construction

Both grammars have a single nonterminal `S` and two rules per tile
`t ∈ P`:

| Grammar  | Recursive rule                                           | Base rule                                  |
|----------|----------------------------------------------------------|--------------------------------------------|
| `topCFG` | `S → t.top.inl ++ S ++ [.inr t]`                         | `S → t.top.inl ++ [.inr t]`                |
| `botCFG` | `S → t.bot.inl ++ S ++ [.inr t]`                         | `S → t.bot.inl ++ [.inr t]`                |

(`t.top.inl` is shorthand for `t.top.map (Symbol.terminal ∘ Sum.inl)`,
etc.)

A derivation of `S` to a terminal-only string in `topCFG P` traces out a
non-empty sequence of tiles `t₁, t₂, …, t_k` (all from `P`) and yields

```
t₁.top ++ t₂.top ++ ⋯ ++ t_k.top   ++   t_k :: ⋯ :: t₂ :: [t₁]
```

(the α-symbols first, then the tile markers in *reverse* order). The
reverse order is forced by the recursive rule shape: each step adds
`t.top.inl` to the left and `[.inr t]` to the right of the recursive
`S`, so outer tiles sit at the outer ends.

## Correctness sketch

* **Forward** (PCP solution `A` ⟹ word in both languages). Build the
  string `w = (tau1 A).inl ++ A.reverse.inr`; by induction on `A`,
  `topCFG P` derives `w`. Since `tau1 A = tau2 A`, `botCFG P` derives
  the same `w`.

* **Backward** (word in both languages ⟹ PCP solution). The
  language-characterisation lemma shows
  `w ∈ (topCFG P).language ↔ ∃ A nonempty in P, w = (tau1 A).inl ++ A.reverse.inr`
  (and similarly for `botCFG` with `tau2`). Equating the two
  representations of `w` and splitting at the `.inl`/`.inr` boundary
  forces the same `A` for both grammars and `tau1 A = tau2 A`, hence a
  PCP solution.
-/

namespace CFG.PcpReduction

open PCP ContextFreeGrammar

variable {α : Type}

/-! ## Terminal alphabet -/

/-- The terminal alphabet of the reduced CFG-intersection instance:
PCP symbols on the `.inl` side, tile markers on the `.inr` side. -/
abbrev Term (α : Type) := α ⊕ Tile α

/-! ## Stack concatenation parameterised by a tile projection -/

/-- Concatenate `proj t` for each tile in the stack. Specialises to
`tau1` (with `proj = Tile.top`) and `tau2` (with `proj = Tile.bot`). -/
def tauProj (proj : Tile α → Word α) : Stack α → Word α
  | []      => []
  | t :: A  => proj t ++ tauProj proj A

@[simp] lemma tauProj_nil (proj : Tile α → Word α) :
    tauProj proj ([] : Stack α) = [] := rfl

@[simp] lemma tauProj_cons (proj : Tile α → Word α) (t : Tile α) (A : Stack α) :
    tauProj proj (t :: A) = proj t ++ tauProj proj A := rfl

@[simp] lemma tauProj_append (proj : Tile α → Word α) (A B : Stack α) :
    tauProj proj (A ++ B) = tauProj proj A ++ tauProj proj B := by
  induction A with
  | nil => simp
  | cons t A ih => simp [ih, List.append_assoc]

@[simp] lemma tauProj_top (A : Stack α) : tauProj Tile.top A = tau1 A := by
  induction A with
  | nil => rfl
  | cons t A ih => simp [tau1, ih]

@[simp] lemma tauProj_bot (A : Stack α) : tauProj Tile.bot A = tau2 A := by
  induction A with
  | nil => rfl
  | cons t A ih => simp [tau2, ih]

/-! ## Rule constructors -/

/-- The recursive rule generated by a tile `t`:
`S → (proj t).inl ++ [S] ++ [.inr t]`. -/
def recRule (proj : Tile α → Word α) (t : Tile α) :
    ContextFreeRule (Term α) Unit :=
  ⟨(),
    (proj t).map (fun a => Symbol.terminal (Sum.inl a))
      ++ [Symbol.nonterminal ()]
      ++ [Symbol.terminal (Sum.inr t)]⟩

/-- The base rule generated by a tile `t`:
`S → (proj t).inl ++ [.inr t]`. -/
def baseRule (proj : Tile α → Word α) (t : Tile α) :
    ContextFreeRule (Term α) Unit :=
  ⟨(),
    (proj t).map (fun a => Symbol.terminal (Sum.inl a))
      ++ [Symbol.terminal (Sum.inr t)]⟩

/-! ## The grammars

These require `[DecidableEq α]` for the `Finset` of rules. -/

section Grammars
variable [DecidableEq α]

/-- The grammar `genCFG proj P`: single nonterminal `()`, rules
`recRule proj t` and `baseRule proj t` for each `t ∈ P`. -/
def genCFG (proj : Tile α → Word α) (P : Stack α) :
    ContextFreeGrammar (Term α) where
  NT := Unit
  initial := ()
  rules := P.toFinset.image (recRule proj) ∪ P.toFinset.image (baseRule proj)

/-- The "top" grammar: emits `t.top` for each tile. -/
abbrev topCFG (P : Stack α) : ContextFreeGrammar (Term α) := genCFG Tile.top P

/-- The "bot" grammar: emits `t.bot` for each tile. -/
abbrev botCFG (P : Stack α) : ContextFreeGrammar (Term α) := genCFG Tile.bot P

/-! ## Rule-membership characterisation -/

lemma mem_rules_iff (proj : Tile α → Word α) (P : Stack α)
    (r : ContextFreeRule (Term α) Unit) :
    r ∈ (genCFG proj P).rules ↔
      ∃ t ∈ P, r = recRule proj t ∨ r = baseRule proj t := by
  unfold genCFG
  simp only [Finset.mem_union, Finset.mem_image, List.mem_toFinset]
  constructor
  · rintro (⟨t, ht, rfl⟩ | ⟨t, ht, rfl⟩)
    · exact ⟨t, ht, Or.inl rfl⟩
    · exact ⟨t, ht, Or.inr rfl⟩
  · rintro ⟨t, ht, rfl | rfl⟩
    · exact Or.inl ⟨t, ht, rfl⟩
    · exact Or.inr ⟨t, ht, rfl⟩

end Grammars

/-! ## Canonical generated string -/

/-- The canonical string the grammar produces from a stack `A`:
`α`-side concatenation of `proj` followed by reversed tile markers. -/
def canonString (proj : Tile α → Word α) (A : Stack α) : List (Term α) :=
  (tauProj proj A).map Sum.inl ++ A.reverse.map Sum.inr

@[simp] lemma canonString_nil (proj : Tile α → Word α) :
    canonString proj ([] : Stack α) = [] := by
  simp [canonString]

@[simp] lemma canonString_cons (proj : Tile α → Word α)
    (t : Tile α) (A : Stack α) :
    canonString proj (t :: A) =
      (proj t).map Sum.inl ++ canonString proj A ++ [Sum.inr t] := by
  simp [canonString, List.map_append, List.append_assoc]

/-! ## Embedding `Word α` / `Stack α` into the grammar alphabet -/

/-- Lift an α-word to a list of `Symbol`s, using `Sum.inl` then `terminal`. -/
abbrev embedA (w : Word α) : List (Symbol (Term α) Unit) :=
  w.map (fun a => Symbol.terminal (Sum.inl a))

/-- Lift a stack to a list of `Symbol`s, using `Sum.inr` then `terminal`. -/
abbrev embedT (A : Stack α) : List (Symbol (Term α) Unit) :=
  A.map (fun t => Symbol.terminal (Sum.inr t))

@[simp] lemma embedA_append (w₁ w₂ : Word α) :
    embedA (w₁ ++ w₂) = embedA w₁ ++ embedA w₂ := by simp [embedA]

@[simp] lemma embedT_append (A B : Stack α) :
    embedT (A ++ B) = embedT A ++ embedT B := by simp [embedT]

@[simp] lemma embedA_nil : embedA ([] : Word α) = [] := rfl
@[simp] lemma embedT_nil : embedT ([] : Stack α) = [] := rfl

@[simp] lemma embedT_singleton (t : Tile α) :
    embedT [t] = [Symbol.terminal (Sum.inr t)] := rfl

lemma canonString_map_terminal (proj : Tile α → Word α) (A : Stack α) :
    (canonString proj A).map Symbol.terminal =
      embedA (tauProj proj A) ++ embedT A.reverse := by
  simp [canonString, embedA, embedT, List.map_map, Function.comp_def]

/-! ## Forward direction: derive `canonString A` from `S` -/

/-- `Rewrites.input_output` packaged for `recRule`. -/
private lemma recRule_rewrites (proj : Tile α → Word α) (t : Tile α) :
    (recRule proj t).Rewrites [Symbol.nonterminal ()]
      (embedA (proj t) ++ [Symbol.nonterminal ()] ++ [Symbol.terminal (Sum.inr t)]) :=
  ContextFreeRule.Rewrites.input_output

/-- `Rewrites.input_output` packaged for `baseRule`. -/
private lemma baseRule_rewrites (proj : Tile α → Word α) (t : Tile α) :
    (baseRule proj t).Rewrites [Symbol.nonterminal ()]
      (embedA (proj t) ++ [Symbol.terminal (Sum.inr t)]) :=
  ContextFreeRule.Rewrites.input_output

section Grammars
variable [DecidableEq α]

/-- From `[S]`, the grammar derives the "intermediate" form
`embedA (tauProj proj A) ++ [S] ++ embedT A.reverse` for any
`A` whose tiles are all in `P`. -/
private lemma derives_intermediate (proj : Tile α → Word α) (P : Stack α)
    (A : Stack α) (h_mem : ∀ t ∈ A, t ∈ P) :
    (genCFG proj P).Derives [Symbol.nonterminal ()]
      (embedA (tauProj proj A) ++ [Symbol.nonterminal ()] ++ embedT A.reverse) := by
  induction A with
  | nil =>
    simp only [tauProj_nil, embedA_nil, List.reverse_nil, embedT_nil, List.nil_append]
    exact Relation.ReflTransGen.refl
  | cons t A' ih =>
    have ht : t ∈ P := h_mem t (List.mem_cons_self ..)
    have h_mem' : ∀ t' ∈ A', t' ∈ P := fun t' ht' =>
      h_mem t' (List.mem_cons_of_mem _ ht')
    have h_rule : recRule proj t ∈ (genCFG proj P).rules := by
      rw [mem_rules_iff]; exact ⟨t, ht, Or.inl rfl⟩
    -- One Produces step: S ⟶ (proj t).inl ++ S ++ [.inr t]
    have step1 : (genCFG proj P).Produces [Symbol.nonterminal ()]
        (embedA (proj t) ++ [Symbol.nonterminal ()] ++ [Symbol.terminal (Sum.inr t)]) :=
      ⟨recRule proj t, h_rule, recRule_rewrites proj t⟩
    -- Apply IH inside the [S] hole.
    have step2 := ((ih h_mem').append_left (embedA (proj t))).append_right
      [Symbol.terminal (Sum.inr t)]
    have step3 := step1.single.trans step2
    -- Massage the conclusion to match the target.
    have h_eq :
        embedA (proj t)
          ++ (embedA (tauProj proj A') ++ [Symbol.nonterminal ()] ++ embedT A'.reverse)
          ++ [Symbol.terminal (Sum.inr t)] =
        embedA (tauProj proj (t :: A')) ++ [Symbol.nonterminal ()]
            ++ embedT (t :: A').reverse := by
      simp only [tauProj_cons, List.reverse_cons, embedA_append, embedT_append,
                 embedT_singleton, List.append_assoc]
    exact h_eq ▸ step3

/-- The grammar derives `(canonString proj A).map Symbol.terminal` from
`[S]` for any non-empty `A` with tiles in `P`. -/
private lemma derives_canonString_map (proj : Tile α → Word α) (P : Stack α)
    (A : Stack α) (h_ne : A ≠ []) (h_mem : ∀ t ∈ A, t ∈ P) :
    (genCFG proj P).Derives [Symbol.nonterminal ()]
      ((canonString proj A).map Symbol.terminal) := by
  obtain ⟨A', t, rfl⟩ : ∃ (A' : Stack α) (t : Tile α), A = A' ++ [t] :=
    ⟨A.dropLast, A.getLast h_ne, (List.dropLast_append_getLast h_ne).symm⟩
  have ht : t ∈ P := h_mem t (by simp)
  have h_mem' : ∀ t' ∈ A', t' ∈ P := fun t' ht' =>
    h_mem t' (List.mem_append.mpr (Or.inl ht'))
  have h_inter := derives_intermediate proj P A' h_mem'
  have h_rule : baseRule proj t ∈ (genCFG proj P).rules := by
    rw [mem_rules_iff]; exact ⟨t, ht, Or.inr rfl⟩
  have step_base : (genCFG proj P).Produces [Symbol.nonterminal ()]
      (embedA (proj t) ++ [Symbol.terminal (Sum.inr t)]) :=
    ⟨baseRule proj t, h_rule, baseRule_rewrites proj t⟩
  have step_base_in_context :=
    (step_base.append_left (embedA (tauProj proj A'))).append_right (embedT A'.reverse)
  have main_derives := h_inter.trans step_base_in_context.single
  -- The conclusion is in `embedA ++ embedT` form; convert to `canonString.map .terminal`.
  have h_eq :
      embedA (tauProj proj A')
        ++ (embedA (proj t) ++ [Symbol.terminal (Sum.inr t)])
        ++ embedT A'.reverse =
      (canonString proj (A' ++ [t])).map Symbol.terminal := by
    simp only [canonString, tauProj_append, tauProj_cons, tauProj_nil, List.append_nil,
               List.reverse_append, List.reverse_cons, List.reverse_nil, List.nil_append,
               embedA, embedT, List.map_append, List.map_cons, List.map_nil,
               List.map_map, Function.comp_def, List.append_assoc]
  exact h_eq ▸ main_derives

/-- **Forward direction**: for any non-empty stack `A` with tiles in
`P`, the grammar `genCFG proj P` generates the canonical string. -/
lemma genCFG_generates_canonString (proj : Tile α → Word α) (P : Stack α)
    (A : Stack α) (h_ne : A ≠ []) (h_mem : ∀ t ∈ A, t ∈ P) :
    (canonString proj A) ∈ (genCFG proj P).language :=
  derives_canonString_map proj P A h_ne h_mem

end Grammars

/-! ## Backward direction: characterise generated strings -/

/-- No `.nonterminal` symbol occurs in `embedA w`. -/
private lemma not_nonterminal_in_embedA (w : Word α) (n : Unit) :
    Symbol.nonterminal n ∉ embedA w := by
  intro h
  obtain ⟨a, _, ha⟩ := List.mem_map.mp h
  cases ha

/-- No `.nonterminal` symbol occurs in `embedT A`. -/
private lemma not_nonterminal_in_embedT (A : Stack α) (n : Unit) :
    Symbol.nonterminal n ∉ embedT A := by
  intro h
  obtain ⟨t, _, ht⟩ := List.mem_map.mp h
  cases ht

/-- Splitting at a unique element: if `xs ++ [a] ++ ys = us ++ [a] ++ vs`
and `a ∉ xs` and `a ∉ ys`, then `xs = us` and `ys = vs`. -/
private lemma split_at_unique {β : Type} {a : β} {xs ys us vs : List β}
    (h_xs : a ∉ xs) (h_ys : a ∉ ys)
    (heq : xs ++ [a] ++ ys = us ++ [a] ++ vs) :
    xs = us ∧ ys = vs := by
  induction xs generalizing us with
  | nil =>
    cases us with
    | nil => simpa using heq
    | cons u us' =>
      exfalso
      simp only [List.nil_append, List.cons_append, List.cons.injEq] at heq
      obtain ⟨_, h_ys_eq⟩ := heq
      apply h_ys
      rw [h_ys_eq]
      simp
  | cons x xs' ih =>
    cases us with
    | nil =>
      exfalso
      simp only [List.nil_append, List.cons_append, List.cons.injEq] at heq
      apply h_xs
      rw [heq.1]
      simp
    | cons u us' =>
      simp only [List.cons_append, List.cons.injEq] at heq
      obtain ⟨h_xu, hrest⟩ := heq
      have h_xs' : a ∉ xs' := fun h => h_xs (List.mem_cons_of_mem _ h)
      obtain ⟨h_xs_eq, h_ys_eq⟩ := ih h_xs' hrest
      exact ⟨by rw [h_xu, h_xs_eq], h_ys_eq⟩

/-- The two-form invariant describing strings reachable from `[S]`.
We use a disjunction rather than an inductive type to make case analysis
amenable to `rcases` (which handles disjunctions cleanly even when the
indices are non-trivial). -/
private def Form (proj : Tile α → Word α) (P : Stack α)
    (s : List (Symbol (Term α) Unit)) : Prop :=
  (∃ A : Stack α, (∀ t ∈ A, t ∈ P) ∧
    s = embedA (tauProj proj A) ++ [Symbol.nonterminal ()] ++ embedT A.reverse) ∨
  (∃ A : Stack α, A ≠ [] ∧ (∀ t ∈ A, t ∈ P) ∧
    s = embedA (tauProj proj A) ++ embedT A.reverse)

private lemma form_init (proj : Tile α → Word α) (P : Stack α) :
    Form proj P [Symbol.nonterminal ()] := by
  refine Or.inl ⟨[], by simp, ?_⟩
  simp

section Grammars
variable [DecidableEq α]

/-- The invariant `Form` is preserved by a single `Produces` step. -/
private lemma form_step (proj : Tile α → Word α) (P : Stack α)
    {s s' : List (Symbol (Term α) Unit)}
    (h_form : Form proj P s) (h_step : (genCFG proj P).Produces s s') :
    Form proj P s' := by
  obtain ⟨r, h_r, h_rw⟩ := h_step
  -- Identify the rule (recRule or baseRule for some t ∈ P).
  have h_r' : ∃ t ∈ P, r = recRule proj t ∨ r = baseRule proj t := by
    have hh := h_r
    unfold genCFG at hh
    simp only [Finset.mem_union, Finset.mem_image, List.mem_toFinset] at hh
    rcases hh with ⟨t, ht, rfl⟩ | ⟨t, ht, rfl⟩
    · exact ⟨t, ht, Or.inl rfl⟩
    · exact ⟨t, ht, Or.inr rfl⟩
  obtain ⟨t, ht, h_t_rule⟩ := h_r'
  rcases h_form with ⟨A, h_mem, h_s_form⟩ | ⟨A, h_ne, h_mem, h_s_form⟩
  · -- s in the "intermediate" form (Form's first disjunct)
    -- Determine where the rewrite happens via exists_parts.
    obtain ⟨p, q, h_eq_s, h_eq_s'⟩ := h_rw.exists_parts
    -- Substitute the rule
    rcases h_t_rule with rfl | rfl
    · -- r = recRule proj t
      rw [h_s_form] at h_eq_s
      -- h_eq_s : embedA ... ++ [.nonterminal ()] ++ embedT A.reverse = p ++ [.nonterminal ()] ++ q
      -- (Note: (recRule proj t).input reduces to () by struct projection.)
      have h_eq_s_norm :
          embedA (tauProj proj A) ++ [Symbol.nonterminal ()] ++ embedT A.reverse
            = p ++ [Symbol.nonterminal ()] ++ q := h_eq_s
      obtain ⟨h_p_eq, h_q_eq⟩ : embedA (tauProj proj A) = p ∧ embedT A.reverse = q :=
        split_at_unique (not_nonterminal_in_embedA _ _) (not_nonterminal_in_embedT _ _)
          h_eq_s_norm
      subst h_p_eq
      subst h_q_eq
      -- Compute s'
      have h_mem_new : ∀ t' ∈ A ++ [t], t' ∈ P := by
        intros t' ht'
        rcases List.mem_append.mp ht' with h | h
        · exact h_mem t' h
        · simp at h; rw [h]; exact ht
      have h_form_new :
          embedA (tauProj proj (A ++ [t])) ++ [Symbol.nonterminal ()]
            ++ embedT (A ++ [t]).reverse =
          embedA (tauProj proj A) ++ (recRule proj t).output ++ embedT A.reverse := by
        simp only [recRule, tauProj_append, tauProj_cons, tauProj_nil, List.append_nil,
                   List.reverse_append, List.reverse_cons, List.reverse_nil, List.nil_append,
                   embedA, embedT, List.map_append, List.map_cons, List.map_nil,
                   List.append_assoc]
      refine Or.inl ⟨A ++ [t], h_mem_new, ?_⟩
      rw [h_eq_s']
      exact h_form_new.symm
    · -- r = baseRule proj t
      rw [h_s_form] at h_eq_s
      have h_eq_s_norm :
          embedA (tauProj proj A) ++ [Symbol.nonterminal ()] ++ embedT A.reverse
            = p ++ [Symbol.nonterminal ()] ++ q := h_eq_s
      obtain ⟨h_p_eq, h_q_eq⟩ : embedA (tauProj proj A) = p ∧ embedT A.reverse = q :=
        split_at_unique (not_nonterminal_in_embedA _ _) (not_nonterminal_in_embedT _ _)
          h_eq_s_norm
      subst h_p_eq
      subst h_q_eq
      have h_mem_new : ∀ t' ∈ A ++ [t], t' ∈ P := by
        intros t' ht'
        rcases List.mem_append.mp ht' with h | h
        · exact h_mem t' h
        · simp at h; rw [h]; exact ht
      have h_ne_new : A ++ [t] ≠ [] := by simp
      have h_form_new :
          embedA (tauProj proj (A ++ [t])) ++ embedT (A ++ [t]).reverse =
          embedA (tauProj proj A) ++ (baseRule proj t).output ++ embedT A.reverse := by
        simp only [baseRule, tauProj_append, tauProj_cons, tauProj_nil, List.append_nil,
                   List.reverse_append, List.reverse_cons, List.reverse_nil, List.nil_append,
                   embedA, embedT, List.map_append, List.map_cons, List.map_nil,
                   List.append_assoc]
      refine Or.inr ⟨A ++ [t], h_ne_new, h_mem_new, ?_⟩
      rw [h_eq_s']
      exact h_form_new.symm
  · -- s in the "done" form (no nonterminals): contradiction (rewrite needs a nonterminal).
    exfalso
    have h_n_mem : Symbol.nonterminal r.input ∈ s := h_rw.nonterminal_input_mem
    rw [h_s_form] at h_n_mem
    rcases List.mem_append.mp h_n_mem with h1 | h2
    · exact not_nonterminal_in_embedA _ _ h1
    · exact not_nonterminal_in_embedT _ _ h2

/-- The invariant `Form` is preserved by any number of `Produces` steps. -/
private lemma form_preserved (proj : Tile α → Word α) (P : Stack α)
    {s s' : List (Symbol (Term α) Unit)} (h_derives : (genCFG proj P).Derives s s')
    (h_init : Form proj P s) : Form proj P s' := by
  induction h_derives with
  | refl => exact h_init
  | tail _ h_step h_ih => exact form_step proj P h_ih h_step

/-- Any string reachable from `[S]` in the grammar satisfies `Form`. -/
private lemma form_holds (proj : Tile α → Word α) (P : Stack α)
    {s : List (Symbol (Term α) Unit)}
    (h_derives : (genCFG proj P).Derives [Symbol.nonterminal ()] s) :
    Form proj P s :=
  form_preserved proj P h_derives (form_init proj P)

/-- **Language characterisation**: a word `w` is in `(genCFG proj P).language`
iff it is `canonString proj A` for some non-empty stack `A` with tiles in `P`. -/
lemma mem_language_iff_canonString (proj : Tile α → Word α) (P : Stack α)
    (w : List (Term α)) :
    w ∈ (genCFG proj P).language ↔
    ∃ A : Stack α, A ≠ [] ∧ (∀ t ∈ A, t ∈ P) ∧ w = canonString proj A := by
  constructor
  · intro h_mem
    rw [mem_language_iff] at h_mem
    have h_form : Form proj P (w.map Symbol.terminal) := form_holds proj P h_mem
    rcases h_form with ⟨A, _, h_eq⟩ | ⟨A, h_ne, h_mem_A, h_eq⟩
    · -- "Intermediate" form: but the string is all terminals — contradiction.
      exfalso
      have h_n : Symbol.nonterminal () ∈ w.map (Symbol.terminal : Term α → _) := by
        rw [h_eq]; simp
      obtain ⟨a, _, ha⟩ := List.mem_map.mp h_n
      cases ha
    · refine ⟨A, h_ne, h_mem_A, ?_⟩
      have h_term_inj :
          Function.Injective (Symbol.terminal : Term α → Symbol (Term α) Unit) :=
        fun _ _ h => Symbol.terminal.inj h
      have h_map_inj :
          Function.Injective (List.map (Symbol.terminal : Term α → Symbol (Term α) Unit)) :=
        List.map_injective_iff.mpr h_term_inj
      apply h_map_inj
      show (w.map Symbol.terminal : List (Symbol (Term α) Unit))
            = (canonString proj A).map Symbol.terminal
      rw [h_eq]
      simp only [canonString, embedA, embedT, List.map_append, List.map_map,
                 Function.comp_def]
  · rintro ⟨A, h_ne, h_mem, rfl⟩
    exact genCFG_generates_canonString proj P A h_ne h_mem

end Grammars

/-! ## Disjointness of the `Sum.inl` / `Sum.inr` prefixes -/

/-- A list of the form `xs.map Sum.inl ++ ys.map Sum.inr` is uniquely
decomposable: the `inl` prefix and `inr` suffix are determined by the
list. -/
private lemma list_inl_inr_split {β γ : Type} :
    ∀ (xs xs' : List β) (ys ys' : List γ),
    xs.map Sum.inl ++ ys.map Sum.inr = xs'.map Sum.inl ++ ys'.map Sum.inr →
    xs = xs' ∧ ys = ys' := by
  intro xs xs' ys ys' h
  induction xs generalizing xs' with
  | nil =>
    cases xs' with
    | nil =>
      simp only [List.nil_append, List.map_nil] at h
      refine ⟨rfl, ?_⟩
      have h_inr_inj : Function.Injective (Sum.inr : γ → β ⊕ γ) :=
        fun _ _ => Sum.inr.inj
      exact (List.map_injective_iff.mpr h_inr_inj) h
    | cons x' xs'' =>
      exfalso
      simp only [List.nil_append, List.map_nil, List.map_cons, List.cons_append] at h
      -- LHS = ys.map Sum.inr, starts with .inr if nonempty, [] otherwise.
      -- RHS starts with .inl x'. Contradiction.
      cases ys with
      | nil => simp at h
      | cons y ys'' =>
        simp only [List.map_cons, List.cons.injEq] at h
        exact absurd h.1 (fun he => by injection he)
  | cons x xs'' ih =>
    cases xs' with
    | nil =>
      exfalso
      simp only [List.nil_append, List.map_nil, List.map_cons, List.cons_append] at h
      cases ys' with
      | nil => simp at h
      | cons y' ys''' =>
        simp only [List.map_cons, List.cons.injEq] at h
        exact absurd h.1 (fun he => by injection he)
    | cons x' xs''' =>
      simp only [List.map_cons, List.cons_append, List.cons.injEq] at h
      obtain ⟨h_head, h_rest⟩ := h
      have h_x_eq : x = x' := Sum.inl.inj h_head
      obtain ⟨h_xs, h_ys⟩ := ih xs''' h_rest
      exact ⟨by rw [h_x_eq, h_xs], h_ys⟩

/-! ## Main reduction theorem: `PCP ≤_m` CFG-Intersection-Nonemptiness -/

section MainTheorem
variable [DecidableEq α]

/-- **Main reduction theorem**. A PCP instance `P` is solvable iff the
intersection of the two derived context-free grammars `topCFG P` and
`botCFG P` is non-empty.

The construction `(topCFG P, botCFG P)` is the standard Hopcroft–Ullman
reduction: each grammar emits one side (top or bottom) of every tile in
`P`, interleaved with tile markers that *force* both grammars to commit
to the same tile sequence. The `.inl`/`.inr` alphabet split lets us
recover, from any word in both languages, the unique tile sequence
witnessing a PCP solution. -/
theorem hasSolution_iff_intersectionNonempty (P : Stack α) :
    HasSolution P ↔
    ∃ w, w ∈ (topCFG P).language ∧ w ∈ (botCFG P).language := by
  constructor
  · -- PCP solution → some word is in both languages.
    rintro ⟨A, h_ne, h_mem, h_eq⟩
    refine ⟨canonString Tile.top A, ?_, ?_⟩
    · exact genCFG_generates_canonString Tile.top P A h_ne h_mem
    · -- `tau1 A = tau2 A` makes `canonString Tile.top A = canonString Tile.bot A`.
      have h_canon_eq : canonString Tile.top A = canonString Tile.bot A := by
        simp only [canonString, tauProj_top, tauProj_bot, h_eq]
      rw [h_canon_eq]
      exact genCFG_generates_canonString Tile.bot P A h_ne h_mem
  · -- some word in both languages → PCP solution.
    rintro ⟨w, hw_top, hw_bot⟩
    rw [mem_language_iff_canonString] at hw_top hw_bot
    obtain ⟨A_top, h_ne_top, h_mem_top, h_w_top⟩ := hw_top
    obtain ⟨A_bot, _, _, h_w_bot⟩ := hw_bot
    -- Both canonical forms equal `w`, so equal each other.
    have h_canon : canonString Tile.top A_top = canonString Tile.bot A_bot := by
      rw [← h_w_top, h_w_bot]
    -- Unfold canonString and apply disjointness.
    have h_split : (tau1 A_top).map Sum.inl ++ A_top.reverse.map Sum.inr =
                   (tau2 A_bot).map Sum.inl ++ A_bot.reverse.map Sum.inr := by
      simpa only [canonString, tauProj_top, tauProj_bot] using h_canon
    obtain ⟨h_tau, h_rev⟩ := list_inl_inr_split _ _ _ _ h_split
    have h_A : A_top = A_bot := List.reverse_injective h_rev
    refine ⟨A_top, h_ne_top, h_mem_top, ?_⟩
    rw [h_tau, h_A]

/-- Corollary: the intersection-emptiness predicate is equivalent to
the negation of PCP-solvability for the constructed instance. -/
theorem intersectionEmpty_iff_not_hasSolution (P : Stack α) :
    CFG.IntersectionEmpty (topCFG P) (botCFG P) ↔ ¬ HasSolution P := by
  constructor
  · intro h_empty h_sol
    obtain ⟨w, hw_top, hw_bot⟩ := (hasSolution_iff_intersectionNonempty P).mp h_sol
    exact h_empty w ⟨hw_top, hw_bot⟩
  · intro h_no_sol w h_w
    exact h_no_sol ((hasSolution_iff_intersectionNonempty P).mpr ⟨w, h_w⟩)

end MainTheorem

end CFG.PcpReduction
